name: Build App

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
        - uses: actions/checkout@v4
    
        - name: Install .NET Framework Developer Packs
          run: choco install netfx-4.5.2-devpack

        - name: Install Visual Studio 2017 Build Tools
          run: choco install visualstudio2017buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --includeRecommended --includeOptional" -y
    
        - name: Install .NET Core SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '5.x'

        - name: Install dependencies
          run: nuget restore LunaticPlayer.sln

        - name: Build
          run: dotnet build LunaticPlayer.sln
